/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/pokt-network/poktroll/pkg/client/cgo_exports */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 12 "block_client.go"
 #include <client.h>

#line 1 "cgo-generated-wrapper"

#line 3 "block_query_client.go"

 #include <client.h>
 #include <stdint.h>
 #include <errno.h>

#line 1 "cgo-generated-wrapper"

#line 3 "depinject.go"
 #include <client.h>

#line 1 "cgo-generated-wrapper"

#line 6 "errors.go"

 #include <client.h>

#line 1 "cgo-generated-wrapper"

#line 3 "events_query_client.go"

 #include <client.h>
 #include <stdint.h>
 #include <errno.h>

#line 1 "cgo-generated-wrapper"

#line 3 "memory.go"
 #include <client.h>

#line 1 "cgo-generated-wrapper"

#line 3 "tx_client.go"

#include <client.h>
#include <stdlib.h>
typedef void* (*callback_type)(void*, char**);
//void bridge_callback(callback_fn *cb, void* data, char** err);
static void bridge_callback(callback_fn *cb, void* data, char** err) {
    if (cb) {
        cb(data, err);
    }
}

#line 1 "cgo-generated-wrapper"

#line 3 "tx_context.go"
 #include <client.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern go_ref NewBlockClient(go_ref depsRef, char** cErr);
extern go_ref NewBlockQueryClient(char* cometWebsocketURL, char** cErr);
extern go_ref BlockQuery_ClientBlock(go_ref clientRef, int64_t* cHeight, char** cErr);
extern go_ref Supply(go_ref go_ref, char** cErr);
extern go_ref SupplyMany(go_ref* go_refs, int numgo_refs, char** cErr);
extern go_ref Config(go_ref* go_refs, int numgo_refs, char** cErr);
extern GoString GetErrMessage(GoInt code);
extern go_ref NewEventsQueryClient(char* cometWebsocketURLCString);
extern go_ref EventsQueryClientEventsBytes(go_ref clientRef, char* query, char** cErr);

// TODO_IN_THIS_COMMIT: godoc...
//
extern void FreeGoMem(go_ref ref);

// TODO_IN_THIS_COMMIT: godoc...
// TODO_IN_THIS_COMMIT: add seperate constructor which supports options...
//
extern go_ref NewTxClient(go_ref depsRef, char* signingKeyName, char** cErr);
extern go_ref WithSigningKeyName(char* keyName);

// TODO_IN_THIS_COMMIT: godoc...
// TODO_IMPROVE: support multiple msgs (if top-level JSON array).
//
extern go_ref TxClient_SignAndBroadcastAny(go_ref txClientRef, char* msgAnyJSON, char** cErr);
extern go_ref TxClient_SignAndBroadcast(go_ref txClientRef, uint8_t* msgBz, int msgBzLen, char* typeUrl, callback_fn* callbackFn, char** cErr);

// TODO_IN_THIS_COMMIT: godoc...
// TODO_IN_THIS_COMMIT: add seperate constructor which supports deps...
// func NewTxContext(depsRef C.go_ref, cErr **C.char) C.go_ref {
//
extern go_ref NewTxContext(char* tcpURL, char** cErr);

#ifdef __cplusplus
}
#endif
